spring:
  config:
    activate:
      on-profile: local
oauth2:
  security:
    resource-server:
      jwk-set-uri: https://accounts.auratest.dev/realms/aura/protocol/openid-connect/certs
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/
# configurations for the backend keycloak client
keycloak:
  client:
    serverUrl: ${KEYCLOAK_CLIENT_SERVER_URL}
    realm: ${KEYCLOAK_CLIENT_REALM}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}