spring:
  config:
    activate:
      on-profile: local
oauth2:
  security:
    resource-server:
      jwk-set-uri: https://accounts.auratest.dev/realms/aura/protocol/openid-connect/certs
    enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/