server:
  port: 8080
spring:
  application:
    name: report-api
  jpa:
    show-sql: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console.enabled: true
oauth2:
  security:
    enabled: true
  jwt:
    secret: ${JWT_SECRET}