spring:
  config:
    activate:
      on-profile: cloud
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/
oauth2:
  security:
    enabled: false # TODO: to be enabled after development phase

# configurations for the backend keycloak client
keycloak:
  client:
    serverUrl: ${KEYCLOAK_CLIENT_SERVER_URL}
    realm: ${KEYCLOAK_CLIENT_REALM}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}