server:
  port: 8080
spring:
  application:
    name: report-api
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console.enabled: true