spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
oauth2:
  security:
    resource-server:
      jwk-set-uri: ${JWK_SET_URI}
    enabled: true
# configurations for the backend keycloak client
keycloak:
  client:
    serverUrl: ${KEYCLOAK_CLIENT_SERVER_URL}
    realm: ${KEYCLOAK_CLIENT_REALM}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
