server:
  port: 8080
spring:
  application:
    name: report-service
  profiles:
    active:
      - cloud
  jpa:
    show-sql: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console.enabled: true
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
#    info:
#      env:
#        enabled: true
info:
  app:
    name: report-service
    description: report microservice
    version: 1.0.0
oauth2:
  security:
    enabled: true
  jwt:
    secret: ${JWT_SECRET}