server:
  port: 8080
  max-http-request-header-size=: 16KB
spring:
  liquibase:
    enabled: false
  application:
    name: report-service
  profiles:
    active:
      - cloud
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    show-sql: true
  threads:
    virtual:
      enabled: true
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      enabled: true
#    info:
#      env:
#        enabled: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  enabled: true
info:
  app:
    name: report-service
    description: report microservice
    version: 1.0.0