# run testing on feature branch
# run testing on PRs to main trunk on the merge commit
name: branch test
run-name: running tests on branch ${{ github.ref_name }}
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    types:
      - "opened"
      - "edited"
      - "synchronize"
    branches:
      - "main"
jobs:
  test:
    defaults:
      run:
        working-directory: ./report-api
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Run tests
        run: mvn test
      - name: Test mvn build
        run: mvn -B package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Test docker container build
        uses: docker/build-push-action@v5
        with:
          context: ./report-api
          push: false
